version: '3.8'

services:
  mensajeria_service:
    build:
      context: ..
      dockerfile: mensajeria_service/Dockerfile
    ports:
      - "8012:8012"
    environment:
      - LOGGING_WS_URL=ws://logging_service:8099/ws/logs
    volumes:
      - ../app:/app/shared
      - .:/app/mensajeria_service
    depends_on:
      - logging_service

networks:
  default:
    name: hellen_network
    external: true
