version: "3.9"

services:
  osrm_cuba:
    image: osrm/osrm-backend
    container_name: bunker-osrm_cuba
    command: osrm-routed /data/cuba.osrm
    volumes:
      - /home/mnf/HellenData/osrm/cuba:/data/cuba
      - /home/mnf/HellenData/StanfordNLP:/models/stanza
      - /home/mnf/HellenData/osrm:/maps
      - /home/mnf/HellenData/chroma_store:/chroma_store
      - /home/mnf/HellenData/qdrant_store:/qdrant_store
      - /home/mnf/HellenData/sqlite_store:/sqlite
    networks:
      - hellen_network

networks:
  hellen_network:
    external: true

