version: "3.9"

services:
  map_service:
    image: ghcr.io/${GHCR_OWNER}/hellencommerce-map_services:latest
    container_name: bunker-map_service
    build:
      context: ./map_service
    image: hellen-map
    container_name: map_service
    ports:
      - "5005:5000"
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    volumes:
      - ./app:/app/app
      - ./data/logs:/app/logs
      # - ./data/sqlite_store:/sqlite
      # - /home/mnf/HellenData/StanfordNLP:/models/stanza
      # - /home/mnf/HellenData/osrm:/maps
      # - /home/mnf/HellenData/chroma_store:/chroma_store
      # - /home/mnf/HellenData/qdrant_store:/qdrant_store
      # - /home/mnf/HellenData/sqlite_store:/sqlite
    networks:
      - hellen_network

networks:
  hellen_network:
    external: true
