version: "3.9"

services:
   intent_service:
    build:
      context: .
      dockerfile: intent_service/Dockerfile
    image: hellen-intent
    container_name: intent_service
    ports:
      - "9010:9010"
    volumes:
      - ./app:/app/app
      - ./models:/app/models
    networks:
      - hellen_net

networks:
  hellen_net:
    external: true
