version: "3.9"

services:
  qdrant_service:
    image: qdrant/qdrant:latest
    container_name: qdrant_service
    ports:
      - "6333:6333" # Puerto para la API REST (comunicación interna y externa)
      - "6334:6334" # Puerto opcional para gRPC (alto rendimiento)
    volumes:
      # Carpeta local en tu proyecto para guardar los vectores de HellenCommerce
      - ./data/qdrant_storage:/qdrant/storage
    environment:
      # Opcional: Desactiva el envío de telemetría anónima
      - QDRANT__TELEMETRY_DISABLED=true
    networks:
      - hellen_network

networks:
  hellen_network:
    external: true
