version: '3.8'

services:
  contacto_service:
    build:
      context: ..
      dockerfile: contacto_service/Dockerfile
    ports:
      - "8011:8011"
    environment:
      - LOGGING_WS_URL=ws://logging_service:8099/ws/logs
    volumes:
      - ../app:/app/shared
      - .:/app/contacto_service
    depends_on:
      - logging_service

networks:
  default:
    name: hellen_network
    external: true
