version: '3.8'

services:
  despedida_service:
    build:
      context: ..
      dockerfile: despedida_service/Dockerfile
    ports:
      - "8019:8019"
    environment:
      - LOGGING_WS_URL=ws://logging_service:8099/ws/logs
    volumes:
      - ../app:/app/shared
      - .:/app/despedida_service
    depends_on:
      - logging_service

networks:
  default:
    name: hellen_network
    external: true
