version: '3.8'

services:
  notificacion_service:
    build:
      context: ..
      dockerfile: notificacion_service/Dockerfile
    ports:
      - "8016:8016"
    environment:
      - LOGGING_WS_URL=ws://logging_service:8099/ws/logs
    volumes:
      - ../app:/app/shared
      - .:/app/notificacion_service
    depends_on:
      - logging_service

networks:
  default:
    name: hellen_network
    external: true
