version: '3.8'

services:
  venta_service:
    build:
      context: ..
      dockerfile: venta_service/Dockerfile
    ports:
      - "8013:8013"
    environment:
      - LOGGING_WS_URL=ws://logging_service:8099/ws/logs
    volumes:
      - ../app:/app/shared
      - .:/app/venta_service
    depends_on:
      - logging_service

networks:
  default:
    name: hellen_network
    external: true
