version: '3.8'

services:
  worker_service:
    build:
      context: ..
      dockerfile: worker_service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - LOGGING_WS_URL=ws://logging_service:8099/ws/logs
    volumes:
      - ../app:/app/shared
      - .:/app/worker_service
    depends_on:
      - logging_service

networks:
  default:
    name: hellen_network
    external: true
